spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/study_olle
    username: study_olle
    password: 1susdp1djrqjfwk1!Q
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: tp.bmsg@gmail.com
    password: myqlkmqeyeuipxwh
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

logging:
  level:
    org:
      hiberante:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jwt:
  token:
    header: X-SEUNGGU-AUTH
    issuer: seunggu
    client-secret: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
    expiry-seconds: 0


my-app:
  admin-email: admin@email.com
  admin-password: 123456789
  admin-username: admin
  user-username: user@email.com
  user-userPassword: user
  client-id: myApp
  client-secret: pass
server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
  port: 9090